### ISSUE TITLE
What - I see no snakes!

### ISSUE THREAD

**Issue by flikka** [pgdr/ssdd16#1]
Somehow it did not work on my ordinateur. Ein MAC, python 3.5.1. Is it related to the difference in how integer division is handled in python 3.x vs 2.7?

```
Kristian-Flikkas-MacBook-Pro:ssdd16 kristian$ python qtgame/qtgame.py 
Welcome to QtSnake!

Press W/Up   to move down
Press S/Down to move up
Press Q/Esc  to quit
Press Space  to toggle solution (DP)
Traceback (most recent call last):
  File "/Users/kristian/ssdd16/qtgame/snake_game.py", line 43, in update
    val = self._model.snakeHeadValue()
  File "/Users/kristian/ssdd16/qtgame/snake_model.py", line 35, in snakeHeadValue
    return self._grid[i][j]
TypeError: list indices must be integers or slices, not float
Traceback (most recent call last):
  File "/Users/kristian/ssdd16/qtgame/snake_game.py", line 43, in update
    val = self._model.snakeHeadValue()
  File "/Users/kristian/ssdd16/qtgame/snake_model.py", line 35, in snakeHeadValue
    return self._grid[i][j]
TypeError: list indices must be integers or slices, not float
Traceback (most recent call last):
```

(and on it goes)

**Comment by flikka** [comment]
Fixed with 54a5d161621ec2b5c3a0942be66f39e16c82e4fe

Good times.
